# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attendeddates',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.Date'),
        ),
    ]
