# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_auto_20170717_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeddates',
            name='date',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
