# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0003_auto_20170731_0641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendedDates',
            new_name='AttendedDate',
        ),
    ]
