# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0004_auto_20170803_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeddate',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 23)),
            preserve_default=False,
        ),
    ]
