# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0005_attendeddate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeddate',
            name='attendee',
        ),
        migrations.AddField(
            model_name='attendeddate',
            name='attendees',
            field=models.ManyToManyField(to='attendanceapp.Attendee'),
        ),
    ]
