# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='group',
            field=models.CharField(choices=[('C', 'Cubbies'), ('S', 'Sparks'), ('T', 'TNT'), ('Tr', 'Trek'), ('J', 'Journey')], default='C', max_length=2),
            preserve_default=False,
        ),
    ]
