# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='group',
            field=models.CharField(choices=[('cubbies', 'Cubbies'), ('sparks', 'Sparks'), ('tnt', 'TNT'), ('trek', 'Trek'), ('journey', 'Journey')], max_length=7),
        ),
    ]
