# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170427_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendee')),
            ],
        ),
    ]
