# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20170508_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceday',
            old_name='attendee',
            new_name='attendee_id',
        ),
    ]
